### ISSUE TITLE
Interlaced video incorrectly handled

### ISSUE THREAD

**Issue by Sharc99** [mltframework/shotcut#1422]
Rendering of interlaced video sources of format YV12 (4:2:0) or YV16 (4:2:2) to interlaced YV12 (4:2:0) using libx264 is flawed. There is significant chroma crosstalk/contamination between the fields, The functionality is essential for rendering captured interlaced VHS sources to interlaced YV12 h.264 video, for example. Setting the source file properties manually does not help / has no effect.
Windows11, all Shotcut versions, including 22.12.21.

**Comment by ddennedy** [comment]
This was already fixed for the next version for which there is a beta that you can test.

**Comment by Sharc99** [comment]
Thanks. Will test soon. Shotcut is really great.

**Comment by Sharc99** [comment]
I made some test with beta 23.04.03.
- It works now for YV12 4:2:0 interlaced AVC (h264) sources.
- It still fails for lossless YUV 4:2:2 and 4:2:0 interlaced sources in .avi container, even though I set the input format (properties) accordingly (interlaced top field first).

**Comment by bmatherly** [comment]
I am willing to look into this if you can provide some test clips and instructions to reproduce.

**Comment by Sharc99** [comment]
Thank you for your kind offer.
I stand corrected. The _conversion_ works correctly for 4:2:2 and 4:2:0 sources with the latest Beta, so this is solved, thanks.
I am just not sure whether the Preview and Sopes->Video Zoom show the scanlines and colors right for 4:2:2 .avi sources. 
I attach a testfile. The source properties have to be set manually to interlaced, top field first as the .avi does not provide the corresponding signalling. Export is h264 interlaced TFF which works correctly with the latest Beta., The fields of the h264 encode can be cleanly separated again as a test. So the main issue (chroma mingling between fields) of the previous version got solved.
[0) 422i_.zip](https://github.com/mltframework/shotcut/files/11198878/0.422i_.zip)

**Comment by Sharc99** [comment]
> The player always operates in 4:2:0. And the video zoom scope takes its values from the player. So the chroma samples will always be shared between 4 pixels in a box.
> 
> So if your source is 4:2:2, you will see some chroma bleeding in the preview/zoom scope.

This explains it. Thank you

**Comment by Sharc99** [comment]
There is another similar issue I like to report:
The latest Beta of Shotcut processes interlaced 4:2:2 and interlaced 4:2:0 sources correctly, as discussed.
However, when opening a _virtual 4:2:0 interlaced .avi_ from the AVFS (Avisynth Virtual File System) the chroma is mingled between the fields as before.
I am using the AVFS for opening Avisynth scripts (.avs) in Shotcut, because Shotcut cannot read Avisynth scripts directly.
I am aware that this may be beyond the scope of Shotcut, but because the AVFS method works well with other video tools which do not directly read .avs scripts I thought I would bring this up as it may be I bug. Otherwise never mind.

**Comment by ddennedy** [comment]
That is not something in our control. It is somewhere between FFmpeg and AVFS.

**Comment by Sharc99** [comment]
ok. 
A minor issue with Beta 23.04.03 though:
a) ffv1 interlaced 4:2:0 in .avi container has fields bleeding when exporting to x264 YV12 interlaced. Setting the source properties manually to interlaced TFF does not help.
b)  ffv1 interlaced 4:2:0 in .mkv container is correct.
c)  ffv1 interlaced 4:2:2 is correct for .avi and .mkv
Maybe a) is a bug?

**Comment by Sharc99** [comment]
maybe, yes.
