### ISSUE TITLE
BUG: Japanese text error

### ISSUE THREAD

**Issue by datietou** [mltframework/shotcut#163]
When use dynamic text filter, when I input such as "にほん", or other odd number of Japanese text, and split the video track, the dynamic text filter in new one clip does not show correctly, it shows 

![20151217182245](https://cloud.githubusercontent.com/assets/7865888/11867436/f2cb47d2-a4eb-11e5-8b0c-b9e45e04b2b8.jpg)

same error ocurs when drag the video file to timeline which use odd number of Japanese text,
such as にほん.mp4  に3ほん.MP4     にほん2.MP4
And timeline is black.

**Comment by ddennedy** [comment]
Unable to reproduce using v15.12.09 (unreleased, interim version) on Windows 7 with US/English region/language setting in Windows. I also just tested on v15.11 release on Windows with no problem. Specify your OS, OS version, and Shotcut version.

**Comment by datietou** [comment]
1》I test v15.11.03 on windows 8.1 enterprise x64 system with GTX660, 
When I change "Control Panel->CLOCK&LANGUAGE&LOCATION->Format" from "same as windows language" to 
"en-US" dynamic text filter shows Japanese ok
2》but Shotcut's dynamic text filter still cannot use third-party input method software to input
 other language such as Japanese, only when the Mouse Right click the textarea and then can input Japanese.Weird, QML problem???
       There also seems a conversion error on libmltxml when I use other system Format than "en-US", 
I debug into libmltxml->consumer_xml.c->output_xml(),  my steps:
1. open a video;
2. drag it to timeline;
3. place a dynamic text and draw "にほん"
4. split the clip
5. debug into output_xml 
xmlDocDumpMemoryEnc( doc, &buffer, &length, "utf-8" );
print the buffer, and it shows text にほ??
when I change xmlDocDumpMemoryEnc( doc, &buffer, &length, "utf-8" ) to:
xmlDocDumpMemory( doc, &buffer, &length)
the buffer shows にほ, lost ん;
This only happens on the odd number of japanese text, always lost the last one.

So I thought libxml2 conversion may be some error ocurs, LC_NUMBER???  but I'm not very familiar with mlt framework now,So can you give me some tips? thanks.

**Comment by ddennedy** [comment]
Are you able to recompile libmltxml.dll by doing ```make -C src/modules/xml all install```?
If so, try to change line 244 of src/modules/xml/consumer_xml.c: from
```value = filter_restricted( mlt_properties_get_value( properties, i ) );```
to
```value = mlt_properties_get_value( properties, i );```

**Comment by datietou** [comment]
Your tips solve the problem but another bugs coming, actually it's hard to debug.
I build the newest shotcut and mlt plugins with mingw32(i686-4.9.2-posix-dwarf-rt_v4-rev4), and debugged with QT5.5 mingw32 4.9.2, but it's extremely not stable than your release build.

The newest one I build is not completely, only 15/24 mlt plugins success because lack of windows version of third party library.

I also compile the old version shotcut which use QT5.2.x with the mxe compiler and mlt prebuild binary download from shotcut.org successfully.But the newest script build failure because of the new mingw compiler(I follow the tips to build mingw cross compiler).

I think a good open source project like shotcut must have a good method to compile it fully and easily, then you can debug it, that's the basic requirement.I dont think dev people always cool, if I  solve some bugs, of course I will sumbit it.But the compiling process is too complex for some guys like me.

It is better to use QT project.So can you put your full project or other usefull compile method here?

**Comment by ddennedy** [comment]
Are you Jefferson Lee on G+? Yes, Shotcut dev and debug is not easy on Windows, but a prebuilt SDK provided by me makes it easier. It is generally much easier on Linux and OS X. Much of this difficulty is due to the large number of library dependencies.

As for the bug, as I recall, that char filter was primarily to deal with strings that were not known to be UTF-8 compliant being put into MLT properties. I think that was mainly from libavformat metadata strings (e.g., title) being passed directly from the media file with no regard to text encoding (probably it is unknown). Maybe I should only apply the filter to these metadata properties, which Shotcut does not currently serialize.

**Comment by datietou** [comment]
Thank you for your suggestion, Do you have script to cross compile mlt plugin and can you update the mingw crosscompiler download link on this page:http://www.shotcut.org/bin/view/Shotcut/CrossCompile ?

**Comment by ddennedy** [comment]
I noticed that file update that mxe-gcc-5.1.0-x64.tar.bz2 was missing in my S3 bucket. So, I uploaded it. The build script is in shotcut scripts/build-shotcut.sh. Run it with "-o Win64" to cross-compile; add "-s" to build the SDK, which includes the source trees with build.

**Comment by ddennedy** [comment]
Fixed in MLT https://github.com/mltframework/mlt/commit/a71d66ea4a11301bee9fcc08a7c316a1f58bf23a
I can give you a new build tomorrow from our nightly build server to confirm.

**Comment by ddennedy** [comment]
Give this a try:
http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-win64-151223.exe

**Comment by datietou** [comment]
Odd number of Japanese video file name and dynamic text test ok, and still cannot use third party software input and the system input software as I mentioned.Only when the app lost focus and get focus, it can input another language.Is it QT qml problem?

**Comment by ddennedy** [comment]
I do not know anything about input software, but it must Qt-related. It could be a quirk with how we use QQuickWidget to host QML content in a QWidgets-based app. I suggest you experiment with a Qt sample app. There is one named "Qt Quick Widgets Example" that comes with Qt Creator.

**Comment by datietou** [comment]
3D text filter has the same problem too.

**Comment by ddennedy** [comment]
3D Text filter on v15.12.23?

**Comment by datietou** [comment]
Yes

**Comment by ddennedy** [comment]
Strange. I have no idea what could be causing that. What about Overlay HTML?

**Comment by datietou** [comment]
When I input にほん, 
1. 3D text filter(HTML) shows ???.
2. HTML overlay shows にほん.

HTML overlay shows ok.

**Comment by ddennedy** [comment]
This might be a limitation of the fonts used by 3D Text. We use fonts supplied by the [three.js text geometry example](http://threejs.org/examples/webgl_geometry_text2.html) as created by [typeface.js](http://typeface.neocracy.org:81/) and [facetype.js](http://gero3.github.io/facetype.js/). Can you please test this by making a copy of that example modified to contain your characters and view in a web browser?

**Comment by datietou** [comment]
I dont familiar with html, so change qml directly.
Change font to another english ttf, it's ok.
change to another language font, it's invisible.
I test at least 20 kinds of another languge ttf files, it's hard to find a suitable one can show. All are invisible.

**Comment by datietou** [comment]
And I think you're right, it's the font js file problem.

**Comment by datietou** [comment]
Can you upload the new mlt prebuild binary?The old one is 2012's.

**Comment by ddennedy** [comment]
The links to the x64 pre-built libraries are now listed at the bottom of this page: http://shotcut.org/bin/view/Shotcut/CrossCompile

**Comment by datietou** [comment]
Is there 32 bit shotcut sdk?

**Comment by ddennedy** [comment]
No, when doing the Qt 5.5 upgrade, I could not get the 32-bit build to work after a few days of work. Then, I considered that the limited RAM usage of a 32-bit process is problematic anyways for HD editing, realized x86-64 has been out for 12 years, and decided to abandon 32-bit.
