### ISSUE TITLE
Shortcut crashes on change of video speed

### ISSUE THREAD

**Issue by BalashovK** [mltframework/shotcut#266]
Load a video, go to properties, change speed. It does not crash all the time, but it you change it back and forth, it will surely crash and close the application.

**Comment by BalashovK** [comment]
Issue resolved in Shortcut 16.07.01 (I have done excessive stress testing and can no longer reproduce it. 16.06 was crashing left and right on the same video file).

**Comment by Verron** [comment]
Just wanted to let you know that it is still crashing in shotcut vs 16.07.1

**Comment by bluehippo45** [comment]
Every. Single. F*cking time i slow down a clip, it just crashes, and i end up having to edit the ENTIRE video from the ground up. I've tried everything, but NOTHING is working, when will shotcut finally fix this? This is a huge issue right now for me

**Comment by ddennedy** [comment]
No, because it works for me.
