### ISSUE TITLE
Crash when drag & drop a video into the timeline

### ISSUE THREAD

**Issue by Kokosaffe** [mltframework/shotcut#271]
OS: Win7 64 Bit Home Premium SP1
Shotcut 16.07.01

How the cras happen:
1. Open File (e.g. example.mpeg)
2. Drag & Drop the File from the center-"window" to the timeline

This happen at my system since about 3 days, not always but almost always, before it didn't happen (but I use shotcut only since 1 month).

[shotcut-log.txt](https://github.com/mltframework/shotcut/files/350911/shotcut-log.txt)

**Comment by Pathduck** [comment]
Constant crashes when adding to the timeline occurs on my system too.

Windows 10 Pro 64-bit
Intel Core i7 4790K @ 4.00GHz
16,0GB Dual-Channel DDR3 @ 799MHz (10-10-10-30)
4095MB NVIDIA GeForce GTX 970 (MSI)
Shotcut 16.06.08

It is not just drag and drop to timeline from player, also drag and drop from playlist, adding a Video or Audio track. Sometimes it happens constantly, sometimes it works like expected so hard to nail down. But Shotcut is basically unusable when it occurs.

One thing I've suspected is running Windows 10 DPI scaling to 150%. But I have tried at 100% and still crashing occurs.

**Comment by ddennedy** [comment]
All current developers are unable to reproduce this bug, but I will leave it open to collect all "does not work for me at all on Windows reports." Who knows; maybe someone affected by this will debug it and submit a patch.

**Comment by Dionysusnu** [comment]
still happens on 18.06.01
windows 10 home 64-bit
shotcut 18.06.01
[shotcut-log.txt](https://github.com/mltframework/shotcut/files/2065750/shotcut-log.txt)

**Comment by ddennedy** [comment]
@Dionysusnu this is a known bug in that version. You need to upgrade to v18.06.02

**Comment by kwacky1** [comment]
Not sure what the deal is, but was getting this error with videos I have taken with my android phone and then downloaded via Google Photos to my computer.

**Comment by ddennedy** [comment]
@kwacky1 The crash you reported is fixed for the next version 19.02

**Comment by circl-lastname** [comment]
This still happens for me
20.02.21
Ubuntu 20.04

**Comment by survivor303** [comment]
Yep, Problem is back on Linux side too, cannot drag or from hamburger "add videotrack".
Just crash and not say reason for it.

**Comment by ddennedy** [comment]
@circl-lastname and @survivor303  see #896 
The problem is probably that you do not have frei0r-plugins installed. The builds provided by this project include frei0r plugins, but a distro package often fails to include that dependency since it is indirect.

**Comment by circl-lastname** [comment]
> @circl-lastname and @survivor303 see #896
> The problem is probably that you do not have frei0r-plugins installed. The [builds provided by this project](https://shotcut.org/downloads/) include frei0r plugins, but a distro package often fails to include that dependency since it is indirect.

Thank you!

**Comment by mikolajs** [comment]
Thanks! In Ubuntu 20.04 the package is not installed auto after install Shotcut.

**Comment by artemioestrella** [comment]
> This still happens for me
> 20.02.21
> Ubuntu 20.04
> 
> Videos play fine from playlist

sudo apt-get install frei0r-plugins
