### ISSUE TITLE
Audio not fading from cross with clip

### ISSUE THREAD

**Issue by lnx64** [mltframework/shotcut#333]
On a project I just did, a quick one, the fade out at the end for both audio and video, did not get applied whatsoever.  It's in the MLT however.

This is the project I edited, which I ended up pushing as is anyway: https://www.youtube.com/watch?v=vH-e2Gcd0_8

Attached is the MLT.
[video.txt](https://github.com/mltframework/shotcut/files/565480/video.txt)

It's the clip at the very end of the video, it was supposed to fade to black and fade out the audio, neither of which seemed to get applied.

Ubuntu 16.04.01, Shotcut 16.10.01..  64-bit..

Can not upgrade to Ubuntu 16.10 for testing, I have radio gear for emergency first response, and it is not compatible with Ubuntu 16.10.

**Comment by lnx64** [comment]
This issue is creeping up again, but now in a different way.  On another project, it is fading out to black, BUT well before 1 second as it's set in the MLT file..  This is really odd.  It seems this may be related to my other report about the faders not working at the beginning of a project.

**Comment by lnx64** [comment]
Update:  On this project, even the transitions are NOT fading the audio in and out.  There appears to be a big problem regarding faders.  Attached is the MLT file.
[nofader.txt](https://github.com/mltframework/shotcut/files/570303/nofader.txt)

**Comment by ldennedy** [comment]
Unfortunately I could only reproduce the audio aspect of what you're describing.. all video transitions are working fine for me. 

The issue you're describing is that when a cross transition is applied with one clip that doesn't have sound, and another that does have sound, the audio doesn't "fade" (or more accurately cross) like it does if just standard fade in and fade out filters are applied.

The way it should behave is that a clip with no audio should cross transition to the clip that does have audio, giving it that "fade in" effect. Instead it just immediately plays. So the bug is that it cannot render a fade in or out when there is no audio to work with? That's my guess...

Mechanically it's a little weird to describe, so sorry about the confusion 😅 Reproduced on Windows 10, Shotcut versions 16.10.01 and 16.11.02.

**Comment by ddennedy** [comment]
This is related to image clips not having audio. It should get fixed with my plan for #325 to change audio mixing.

**Comment by ddennedy** [comment]
This was fixed in MLT for next release.

**Comment by lnx64** [comment]
On 16.12.03, this still isn't working quite as it should, in fact now the transition with an image with no sound, has no sound whatsoever, whereas before it had sound at least.  Before, I could manually add a fade in for sound (or fade out), but now with no sound in the transition itself, the fade ins are ocurring after the video already faded..

Also, this has seemed to mess with the audio faders a little, audio seems to fade out and fade in not quite at the right times.  For example, I have a fade out on a clip that fades to an image, but the audio cuts off before the fade out is fully finished, making it sound harsh.

**Comment by ddennedy** [comment]
I just made another quick test and it works for me. You need to provide steps.

**Comment by lnx64** [comment]
Add video to timeline, nudge to the right a little.  I then add in a simple black backdrop (could be any image), then align the video I nudged to the side of the image on the timeline.  I add some text to the black backdrop.  Then when trying to pull the video aside to make a transition, the transition has NO sound whatsoever.
Video to this part:  https://www.youtube.com/watch?v=mra6Ad3_SBc

This is the other one, where fading out audio doesn't fade to complete silence, thus is not fading out completely.  As you hear, the audio was still at -35 on the VU meter before cutting out.  This isn't expected results, as it should have faded out completely so no "cut" was heard.
Video of this part:  https://www.youtube.com/watch?v=hVfn70Q_Wuo

I hope this helps...

**Comment by lnx64** [comment]
If you can identify from these video captures what is causing the transition and fade outs to not work correctly, and if you know of a workaround, please let me know.  I need to have this project exported and finished by tomorrow morning for my client.  I'll be happy to take any workarounds, otherwise if I release it like this, the client won't approve.

**Comment by ddennedy** [comment]
The cross-fade bug occurs when transitioning from an image to a clip with sound. My testing thus far was focused on going from a clip to image. A workaround for this is to edit the MLT XML, remove the `<property name="accepts_blanks">1</property>` lines, reopen the project, and add a Fade In Audio filter to the transition.

I have not found the root cause of the audio fade out problem, but you can edit the MLT XML to workaround this. For every `<filter>` with a `<property name="shotcut:filter">fadeInVolume</property>`, replace the following lines:
```
      <property name="gain">1</property>
      <property name="end">0</property>
```
with
```
      <property name="level">0=1; 0:-0.1=-60</property>
```

To make the same kind of fix for a fade in, use instead:
```
      <property name="level">0=-60; 0:-0.1=1</property>
```

**Comment by lnx64** [comment]
Thank you for the workaround, you may have just saved my bacon for this project.  (Actually you did save my bacon!)  While most of the time I usually do foolish YouTube videos, it's these higher projects for clients that put the foods on my table, and I rely on it, which is why I'm usually here so often.

I was scared for a second you were going to need the video I was using, as it's around 120GB, lol.  Not to mention classified material right now.
