### ISSUE TITLE
15.07 Text filter not working (not showing text properly)

### ISSUE THREAD

**Issue by jessedubord** [mltframework/shotcut#94]
See video for issue: https://www.youtube.com/watch?v=RyK5Ae36YBM

Details: when the text filter is applied to a clip in the timeline, it either doesn't display the text (comes out distorted), doesn't display the right size font (changing the filter details has no effect), or it doesn't show the text at all.

(Using Shotcut 15.07.02 on Linux Mint 17.2 x64 w/ Cinnamon 2.6.11 desktop environment.)

UPDATE: Seems to be related to the experimental GPU processing feature. When I turn it off, text seems to appear fine. Although, adjusting the font size when I click on the font name to open the dialog box doesn't seem to change the font size in the clip at all.

**Comment by ddennedy** [comment]
Font size is controlled only by the on-screen rectangle control.

**Comment by ddennedy** [comment]
I reproduced it on OS X, but I can also workaround it by resizing slightly.

**Comment by TrappedOnEarth** [comment]
Same problem on Ubuntu 14.04.2, GPU accelerated or not. 3D and regular text doesn't show up correctly. Resizing or making more edits makes the program crash.

**Comment by faridosc** [comment]
here it works fine without gpu acceleration. with gpu acceleration i get the same artifacts but the resizing workaround fixes it.

[using same version of shotcut as jesse but with 64bit archlinux]

**Comment by petrica-celrau** [comment]
V 15.09.11: I'm having very similar problems with the text filter (no GPU processing), the text keeps disapearing though if I reload the xml file the text is still there. Also if I put black text on a white background (Generator -> Color) the text has a slightly gray-transparent background (see the xml part which if I remove it all looks fine:
<property name="track">0</property>
      <property name="argument">telnet</property>
      <property name="geometry">3.65%/33.61%:86.82%x34.91%</property>
      <property name="family">Sans</property>
      <property name="size">377</property>
      <property name="weight">750</property>
      <property name="fgcolour">#ff000000</property>
     ## <property name="bgcolour">#20000000</property>##
      <property name="olcolour">#ff000000</property>
      <property name="pad">0</property>
      <property name="halign">center</property>
      <property name="valign">bottom</property>
      <property name="outline">0</property>
      <property name="mlt_type">filter</property>
      <property name="mlt_service">dynamictext</property>
      <property name="shotcut:filter">dynamicText</property>
    </filter>
    <filter id="filter1

**Comment by ddennedy** [comment]
@petrica-celrau You are seeing a bug in the Text filter UI in v15.09 that was fixed in v15.10. And yes, a translucent gray background is the default that you are free to change as you noticed.

**Comment by petrica-celrau** [comment]
Upgrading fixed the filter, thanks.

**Comment by zhouhuirun2015** [comment]
verified on version 16.05, this problem still exists, not happen every time.
